0.导入相关的库

In [1]:
import cv2                             #导入opencv库,用于读取、显示和处理图像
import numpy as np                     #导入numpy库,用于进行数组操作
import matplotlib.pyplot as plt        #导入matplotlib.pyplot库,用于绘制图像,实现数据可视化

1.图像处理基础

In [2]:
img = cv2.imread('lena.jpg')           #读取图像,参数为图像路径,返回值为图像数组
cv2.imshow('image', img)               #显示图像,参数为窗口名称,图像数组
cv2.waitKey(0)                         #等待用户按键,参数为等待时间,单位为毫秒,0表示无限等待
cv2.destroyAllWindows()                #关闭所有窗口
cv2.imwrite('lena.png', img)           #将图像保存到文件,参数为文件名,图像数组

True

2.图像基本操作

获取图像像素值、提取图像ROI

In [ ]:
img_val = img[100, 100]                #获取图像中(100,100)像素的颜色值,返回值为BGR格式的元组
print('img_val:', img_val)

img_roi = img[100:500, 100:500]        #获取图像中(100,100)到(200,200)的矩形区域,返回值为图像数组
cv2.imshow('img_roi', img_roi)         #显示图像,参数为窗口名称,图像数组


cv2.waitKey(0)                         #等待用户按键,参数为等待时间,单位为毫秒,0表示无限等待
cv2.destroyAllWindows()                #关闭所有窗口

img_val: [ 74  60 162]


通道分离与合并

In [9]:
b,g,r = cv2.split(img)                 #将图像通道分离,返回值为BGR格式的数组
cv2.imshow('b', b)                  
cv2.imshow('g', g)
cv2.imshow('r', r)

img_merged = cv2.merge((r, g, b))      #将图像通道按bgr的顺序合并,返回值为BGR格式的数组
cv2.imshow('img_merged', img_merged)
cv2.waitKey(0)                    
cv2.destroyAllWindows()            

图片缩放、旋转、平移、镜像翻转

In [ ]:
cv2.imshow('img', img)
img_resized = cv2.resize(img, (500, 500))                                                                    #将图像缩放为500x500,返回值为缩放后的图像数组
cv2.imshow('img_resized', img_resized)                                                                  

img_rotated = cv2.rotate(img, cv2.ROTATE_90_CLOCKWISE)                                                       #将图像顺时针旋转90度,返回值为旋转后的图像数组
cv2.imshow('img_rotated', img_rotated)                                                                  

img_flipped = cv2.flip(img, 1)                                                                               #将图像水平翻转,返回值为翻转后的图像数组
cv2.imshow('img_flipped', img_flipped) 

img_translated = cv2.warpAffine(img, np.float32([[1, 0, 100],
                                                 [0, 1, 100]]), 
                                                (img.shape[1], img.shape[0]))                                #将图像平移100像素,返回值为平移后的图像数组
cv2.imshow('img_translated', img_translated) 


cv2.waitKey(0)                    
cv2.destroyAllWindows()            

仿射变换和透视变换

In [ ]:
#仿射变换
pts1 = np.float32([[0, 0], [img.shape[1]-1, 0], [0, img.shape[0]-1]])                                                    #原始图像的三个点,分别对应图像的左上角，右上角，左下角
pts2 = np.float32([[0, 0], [int(0.6*(img.shape[1]-1)), int(0.2*img.shape[0])], [int(0.2*img.shape[1]), int(0.7*(img.shape[0]-1))]])      #目标图像的三个点,分别对应图像的左上角，右上角，左下角
M = cv2.getAffineTransform(pts1, pts2)                                                         #获取仿射变换矩阵,参数为原始图像的三个点和目标图像的三个点,返回值为3x2的变换矩阵
img_affine = cv2.warpAffine(img, M, (img.shape[1], img.shape[0]))                                              #将图像进行仿射变换,参数为原始图像,变换矩阵,目标图像的大小,返回值为变换后的图像
cv2.imshow('img_affine', img_affine)

#透视变换
pts1 = np.float32([[50, 50], [200, 50], [50, 200], [200, 200]])
pts2 = np.float32([[10, 100], [200, 50], [100, 250], [220, 220]])
M = cv2.getPerspectiveTransform(pts1, pts2)
img_perspective = cv2.warpPerspective(img, M, (img.shape[1], img.shape[0]))                                              #将图像进行透视变换,参数为原始图像,变换矩阵,目标图像的大小,返回值为变换后的图像
cv2.imshow('img_perspective', img_perspective)


cv2.waitKey(0)                    
cv2.destroyAllWindows()            

[[ 1.54117647e+00  1.22352941e+00 -1.25882353e+02]
 [-4.17647059e-01  2.44117647e+00  2.23529412e+01]
 [-1.17647059e-04  4.82352941e-03  1.00000000e+00]]


3.图像算术运算

图像基本运算：加减乘除法

In [5]:
gege1 = cv2.imread('gege1.jpg')
gege2 = cv2.imread('gege2.jpg')
gege1 = cv2.resize(gege1, (gege2.shape[1], gege2.shape[0]))

img_add = cv2.add(gege1, gege2)                 #直接相加，超过255的部分取255
cv2.imshow('img_add', img_add)

img_sub = cv2.subtract(gege1, gege2)            #直接相减，低于0的部分取0
cv2.imshow('img_sub', img_sub)

img_mul = cv2.multiply(gege1, gege2)            #直接相乘
cv2.imshow('img_mul', img_mul)

img_div = cv2.divide(gege1, gege2)              #直接相除，低于0的部分取0
cv2.imshow('img_div', img_div)

cv2.waitKey(0)
cv2.destroyAllWindows()

图像位运算：与、或、非、异或

In [28]:
h,w = img.shape[:2]
one = np.ones((h, w), dtype=np.uint8)*255
zero = np.zeros((h, w), dtype=np.uint8)
zero[100:200, 100:200] = np.ones((100, 100), dtype=np.uint8)*100

#掩码操作、图像分割
img_and = cv2.bitwise_and(one, zero) # 与运算，只有当两个像素值都为1时，结果才为1
cv2.imshow('img_and', img_and)
print("与运算结果:",img_and[0,0])

#图像叠加
img_or = cv2.bitwise_or(one, zero) # 或运算，只要有一个像素值为1，结果就为1
cv2.imshow('img_or', img_or)
print("或运算结果:",img_or[0,0])

#图像反色
img_not = cv2.bitwise_not(one) # 非运算，将像素值为1的部分变为0，0的部分变为1
cv2.imshow('img_not', img_not)
print("非运算结果:",img_not[0,0])


#图像差异检测
img_xor = cv2.bitwise_xor(one, zero) # 异或运算，只有当两个像素值不同时，结果才为1
cv2.imshow('img_xor', img_xor)
print("异或运算结果:",img_xor[0,0])



cv2.waitKey(0)
cv2.destroyAllWindows()


与运算结果: 0
或运算结果: 255
非运算结果: 0
异或运算结果: 255


图像混合

In [6]:
wight1 = 0.5
wight2 = 0.5

img_addweight = cv2.addWeighted(gege1, wight1, gege2, wight2, 0)

cv2.imshow('img_addweight', img_addweight)
cv2.waitKey(0)
cv2.destroyAllWindows()

4.图像阈值化